### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by ainesophaur**
switch from using this.redis_pings in favor of this.redis_ping()

### CODE REVIEW

**Comment by msimerson** [comment]
Should   `this.redis_ping()` still be in `register()`?  If it's just throwing an error at startup, it's not doing any good.

**Comment by ainesophaur** [comment]
In my testing, the race condition always occurs when calling redis_ping in
the register. The init hooks for the redis plugin doesn't seem to complete
before ping is called when interacting with redis in the register function

**Comment by msimerson** [comment]
That sounds like your answer is *yes*.

**Comment by ainesophaur** [comment]
Actually, no. I mistakenly left it in when I was doing a 3 way merge from my local branch to my GH fork. I just made commit 0d5ed36c05558529e2cc9741abdfd938fa5b04fb which removes the call within the register method.

**Comment by superman20** [comment]
I'm a Windows user and don't use redis at all.  The new construct throws an uncaught error every time rendering startup impossible.  Not calling:
```
this.merge_redis_ini();
this.redis_ping();
this.register_hook('init_master',  'init_redis_plugin');
this.register_hook('init_child',   'init_redis_plugin');
```
solves the problem for me (and incidentally gets rid of the periodic connection error messages to redis).  I have a patch that adds a `disabled` option to the config and everywhere that is true, it skips any redis calls (including the ones above in `register`), but that might not be quite what you're looking for.

**Pull request merged**
